Draft 2019 Roadmap
reuniverse/reuniverse pull request #30
Opened 2019-07-13 20:55 UTC by ostera

We met today from ~7pm CET until almost ~11pm to:

1. Discuss the first RFC, which ended up in a few small amendments visible in this PR
2. Write a roadmap for the first initial phase of the project
3. Sketch a roadmap for the second

Thanks @ulrikstrid, @p1xelHer0, and @cem2ran

2019-07-13 20:57 UTC, ulrikstrid requested changes

2019-07-13 20:57 UTC, ulrikstrid commented on rfcs/0003-roadmap-2019.md
> +                    Ulrik Strid <ulrikstrid@outlook.com>
ulrik.strid@outlook.com

2019-07-13 20:58 UTC, ulrikstrid submitted a review, later dismissed

2019-07-14 12:58 UTC, ulrikstrid commented on rfcs/0003-roadmap-2019.md
> +[feat-2-package-docs]: #feat-1-package-docs
typo: `#feat-1-package-docs` -> `#feat-2-package-docs`

2019-07-14 12:58 UTC, ulrikstrid commented on rfcs/0003-roadmap-2019.md
> +[feat-3-recent-releases]: #feat-1-recent-releases
typo: `#feat-1-recent-releases` -> `#feat-3-recent-releases`

2019-07-14 20:55 UTC, cem2ran reviewed
👍 Added a few links and made a few suggestions to fix typos.

2019-07-14 20:55 UTC, cem2ran commented on rfcs/0001-reuniverse.md
> +   NixPkgs, or Entropy.
```suggestion
   [Nixpkgs](https://github.com/NixOS/nixpkgs), or [Entropic](https://github.com/entropic-dev/entropic).
```

2019-07-14 20:55 UTC, cem2ran commented on rfcs/0001-reuniverse.md
> +   In the future, additional package sources could be included, such as Opam,
```suggestion
   In the future, additional package sources could be included, such as [Opam](https://github.com/ocaml/opam-repository),
```

2019-07-14 20:55 UTC, cem2ran commented on rfcs/0003-roadmap-2019.md
> +This first roadmap is intended to ellaborate on _what_ needs to be done in
```suggestion
This first roadmap is intended to elaborate on _what_ needs to be done in
```

2019-07-14 20:55 UTC, cem2ran commented on rfcs/0003-roadmap-2019.md
> +* We have a index of Reason packages published to a public url
```suggestion
* We have an index of Reason packages published to a public url
```

2019-07-15 09:35 UTC, cem2ran approved these changes

2019-07-15 09:59 UTC, p1xelHer0 reviewed
These are just some comments about consistent naming:

We should use the same and the "official" name when referring to tools and other projects.
The official site for opam https://opam.ocaml.org/ seems to refer to opam as "opam", all lowercase.
npm https://www.npmjs.com/ refers to npm as "npm" with all lowercase as well.
GitHub seems to refer to themselves as "GitHub" most of the time.

2019-07-15 09:59 UTC, p1xelHer0 commented on rfcs/0001-reuniverse.md
> +   In the future, additional package sources could be included, such as [Opam](https://github.com/ocaml/opam-repository),
Opam -> opam

2019-07-15 09:59 UTC, p1xelHer0 commented on rfcs/0003-roadmap-2019.md
> +* All packages will show where they came from (npm, github, etc)
github -> GitHub or Github?

2019-07-15 09:59 UTC, p1xelHer0 commented on rfcs/0003-roadmap-2019.md
> +* The index is updated periodically.
No period here? We don't use periods in other lists.

2019-07-15 09:59 UTC, p1xelHer0 commented on rfcs/0003-roadmap-2019.md
> +Reuniverse should scan Github for packages marked as using the OCaml language
Github -> GitHub? We have to decide on one.

2019-07-15 09:59 UTC, p1xelHer0 commented on rfcs/0003-roadmap-2019.md
> +closely with work being done by @thangngoc89 on Sketch.sh, and is a point
change this to be a link to https://sketch.sh/? [Sketch.sh](https://sketch.sh/)

2019-07-16 06:01 UTC, ulrikstrid approved these changes

2019-07-16 09:08 UTC, p1xelHer0 approved these changes

2019-07-16 09:24 UTC, merged